version: "2.0.8"

# Your Wi-Fi's SSID and password
wifi_ssid: <redacted>
wifi_password: <redacted>

ssid1_pswd: <redacted>
ssid1_name: <redacted>

ssid2_pswd: <redacted>
ssid2_name: <redacted>

ssid3_pswd: <redacted>
ssid3_name: <redacted>

ssid4_pswd: <redacted>
ssid4_name: <redacted>

# Your domain
domain: .local

# Passwords for appl, ota and homeassistant
app_pswd: <redacted>
ota_pswd: <redacted>
ha_pswd: <redacted>

# UDP server wmbusmeter
wmbus_server:  <redacted>
wmbus_server_port: 7337

# Backup
web_username: <redacted>
web_password: <redacted>

# syslog
syslog_server: <redacted>
syslog_port: <redacted>

# kostal pico connections: http://username:password@kostalpicoip
kostal_url: "http://<redacted>:<redacted>@<redacted>"
kostal_testurl: "https://raw.githubusercontent.com/zibous/ha-kostal-piko-esp/main/kostal/kostaldata.html"

# kostal pico test (static data)
kostal_testurl1: "http://www.ipscon.com/kostal.html"
kostal_testurl2: "http://www.ipscon.com/kostal2.html"

## webserver 3.0 change url to your webserver
webserver_jsurl:  "https://raw.githubusercontent.com/zibous/ha-watermeter/b0e3ed3f9b7c9f8da74bfe37389cee26ec8358e3/esphome/webserver/v3/www.js"
webserver_cssurl: "https://raw.githubusercontent.com/zibous/ha-watermeter/b0e3ed3f9b7c9f8da74bfe37389cee26ec8358e3/esphome/webserver/v3/webserver.css"

# webserver v2 change url to your webserver
## if you have homeassistant installed, you can use it as webserver
## copy the webserver to the homeassistant www folder and use:
## http://homeassistant.local:8123/www/esphome/webserver/v3/www.js
webserver2_jsurl:  "http://homeassistant.local:8123/local/esphome/v2/www.js"

# webserver v1 change url to your webserver
webserver1_jsurl:  "https://espweb.local/esphome/v2/webserver-v1.js"
webserver1_cssurl: "https://espweb.local/esphome/v1/webserver-v1.css"
